- name: configure the backend services
  hosts: backend
  become: yes
  tasks:
   - name: disable the nodejs
     ansible.builtin.command: dnf module disable nodejs -y
  
   - name: enable the nodejs
     ansible.builtin.command: dnf module enable nodejs:20 -y
  
   - name: install nodejs
     ansible.builtin.dnf:
      name: nodejs
      state: installed

   - name: add an user
     ansible.builtin.user:
      name: expense
   