- name: Configure backend server
  hosts: backend
  become: yes
  vars:

  tasks:
  - name: disable the nodejs
    ansible.builtin.command: dnf module disable nodejs -y

  - name: enable the nodejs
    ansible.builtin.command: dnf module enable nodejs:20 -y
  
  - name: install node -js
    ansible.builtin.dnf:
      name: nodejs
      state: installed
  
  - name: add the user
    ansible.builtin.user:
     name: expense
  
  - name: create an app directory
    ansible.builtin.file:
     path: /app
     state: directory
