- name: configure mysql database
  hosts: db
  become: yes
  vars:
    vinni: db.sudheerdevopsengineer.online
  vars_prompt:
  - name: rangola
    prompt: please enter the password
    private: no
  tasks:
    - name: installing my-sql
      ansible.builtin.dnf:
        name: mysql-server
        state: latest
    - name: Start and Enable 
      ansible.builtin.service:
        name: mysqld
        state: started
        enabled: yes
   
    - name: install the dependendices for mysql server
      ansible.builtin.pip:
        name: 
        - PyMySQL
        - cryptography
        executable: pip3.9
   
    - name: DB Connection
      community.mysql.mysql_info:
        login_user: root
        login_password: "{{ rangola }}"
        login_host: "{{ vinni }}"
        filter: version
      ignore_errors: yes
      register: sudheer
   
    - name: store the output
      ansible.builtin.debug:
        msg: " the error that stored {{ sudheer }}"
   
    - name: setup root and password
      ansible.builtin.command: "mysql_secure_installation --set-root-pass {{ rangola }}"
      when: sudheer.failed is true

