- name: configure frontend server 
  hosts: frontend
  become: yes
  tasks:
    - name: download the latest nginx 
      ansible.builtin.dnf:
        name: nginx
        state: latest
    
    - name: start and enable nginx
      ansible.builtin.service:
        name: nginx
        state: started
        enabled: yes

    - name: delete the default html
      ansible.builtin.file:
        path: usr/share/nginx/html
        state: absent

